[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
darling = "0.20.10"
quote = "1.0.38"
syn = {version = "2.0.98", features = ["full"]}
chrono = "0.4"

[[bin]]
name = "declarative_macros"
test = false
bench = false
