name: "microservices: Build & Test"

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main
  #  pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "29.x"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and test code
        run: |
          cargo build --verbose --package microservices
          cargo test --verbose --package microservices
